add disable column in spreadsheet
EyeSeeTea/user-extended-app pull request #197
Opened 2021-03-05 10:25 UTC by jvfdunkley

### :pushpin: References

-   **Issue:** Closes ["Add disable column in spreadsheet"](https://app.clickup.com/t/ewz22j) in ClickUp

### :memo: Implementation 
- I added the disabled column in ImportExport
- For the export function, I just had to pass in all columns instead of filtering by the ones that are not supposed to be shown on export
- For the import I added disabled to the userCredentials field so that it would be copied to the right place when updating a user
- The disabled value would show up as a string when it had to be a boolean so I had to convert it in the getUsersFromCsv function
 
### :art: Screenshots
<img width="603" alt="Screen Shot 2021-03-05 at 11 09 15 AM" src="https://user-images.githubusercontent.com/20975863/110100899-3e1a8a00-7da3-11eb-9090-5a7a4ba29dfc.png">
<img width="1244" alt="Screen Shot 2021-03-05 at 11 23 48 AM" src="https://user-images.githubusercontent.com/20975863/110102603-e5e08980-7d9c-11eb-9aa8-4a9033bccb03.png">

### :fire: How to test it? (If there is any special consideration or the reviewer does not know how to test it)

2021-05-19 08:05 UTC, tokland requested changes

2021-05-19 11:25 UTC, adrianq commented on src/models/userHelpers.js
>          .map((value, key) => (_(["TEXT", "DATE", "URL"]).includes(value.type) ? key : null))
@tokland I would say we can render the boolean columns as a toggle switch. Can you take care of this @jvfdunkley?

2021-05-19 11:34 UTC, tokland requested changes
Some in-line comments. Check with @adrianq, but I think we need some extra work on the import part. In the import table, show a toggle, and make sure a boolean value (not a string) is posted.

2021-05-19 11:34 UTC, tokland commented on src/models/userHelpers.js
> +            o.user.disabled ? { ...o.user, disabled: o.user.disabled.toLowerCase() } : o.user
I'd keep it a boolean, something like: `disabled: o.user.disabled === "true"`

2021-05-19 11:34 UTC, tokland commented on src/models/userHelpers.js
> +            o.user.disabled ? { ...o.user, disabled: o.user.disabled.toLowerCase() } : o.user
Sorry, I hadn't notice before, but this processing for the field disabled could be in "getPlainUserFromRow", right?

2021-05-21 12:42 UTC, tokland approved these changes
I pushed some changes for the toggle, works for me!

2021-06-07 12:25 UTC, merged