Replace Dialog with ConfirmationDialog, part 2
EyeSeeTea/user-extended-app pull request #220
Opened 2021-12-02 08:09 UTC by oventi

### :pushpin: References
-   **Issue:** https://app.clickup.com/t/1t1ynpf

- Switched to ConfirmationDialog instead of Dialog on ImportTable and MultipleSelector

2021-12-02 09:53 UTC, SferaDev requested changes
Please check my comment, also ensure the behaviour is consistent before/after and provide screenshots in the PR.

Thanks!

2021-12-02 09:53 UTC, SferaDev commented on src/legacy/components/ImportTable.component.js
> -        const actions = this.getActionsByState(allowOverwrite, duplicatedUsernamesExist, showProcessButton);
Please clean-up unused methods like this. Also the ``Toggle`` that appeared next to the buttons should be added to the dialog content.

```
                {showOverwriteToggle && !templateUser && (
                    <Toggle
                        label={this.t("overwrite_existing_users")}
                        labelPosition="right"
                        toggled={allowOverwrite}
                        onToggle={this.toggleAllowOverwrite}
                        style={styles.overwriteToggle}
                    />
                )}
```

2021-12-03 10:28 UTC, oventi commented
Have refactored, added the toggle and screenshots. I]'m having trouble with the linter in my editor, however, as of my push, there are no warnings or errors.

2021-12-07 09:40 UTC, SferaDev approved these changes

2021-12-07 09:40 UTC, merged