fix: reload table after action execution
EyeSeeTea/user-extended-app pull request #267
Opened 2023-09-15 18:39 UTC by eperedo

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/865czeue4

### :memo: Implementation

### :video_camera: Screenshots/Screen capture

[User-Extended-App.webm](https://github.com/EyeSeeTea/user-extended-app/assets/461124/f6ffd6b8-2247-4e5f-a50a-a91bf68c70a8)

### :fire: Testing

2023-09-18 20:34 UTC, ifoche requested changes
@eperedo not sure why but with this code when you try to replicate a user from table, instead of the classical replicate from table modal, you get the replicate user from template one. Could you please give it a look?

2023-09-19 01:29 UTC, eperedo commented
> @eperedo not sure why but with this code when you try to replicate a user from table, instead of the classical replicate from table modal, you get the replicate user from template one. Could you please give it a look?

Sorry my bad. I was using the same name action for both modals. Can you try again?

2024-01-22 16:24 UTC, eperedo commented on src/webapp/components/user-list-table/UserListTable.tsx
> +            console.debug("Reloading", reloadKey, reloadTableKey);
I'm using `reloadTableKey` to update the table when actions outside table are executed (old components like replicate from user, set org unit)

2024-01-29 12:50 UTC, tokland approved these changes
All good! Just a minor proposal for an option. Also, can you add .rvmrc with the expected node version?

2024-01-29 12:50 UTC, tokland commented on src/domain/usecases/SaveUserStatusUseCase.ts
> +    public execute(users: User[], disabled: boolean): FutureData<void> {
best practices: `options: {disabled: boolean}`

2024-02-14 11:33 UTC, MiquelAdell approved these changes

2024-02-14 11:35 UTC, MiquelAdell approved these changes

2024-02-14 11:36 UTC, merged