Feat/update feedback component
EyeSeeTea/user-extended-app pull request #282
Opened 2024-05-07 10:48 UTC by mariaozamiz

### :pushpin: References

-   **Issue:** Closes [Feedback tools is not able to upload screenshots](https://app.clickup.com/t/8693egcc4)

### :memo: Implementation

Replace old feedback-tool with feedback-component. 

### :video_camera: Screenshots/Screen capture
<img width="1323" alt="Captura de pantalla 2024-05-07 a las 12 45 40" src="https://github.com/EyeSeeTea/user-extended-app/assets/55712984/82ffe6e4-2bcc-4192-9ab8-eef4ba34c462">

### :fire: Testing

Launch the project and submit your feedback using the feedback component. To ensure the action was successful, navigate to the network tab. Once confirmed, head over to the [ClickUp list](https://app.clickup.com/4528615/v/l/li/170646832) and find there your submitted feedback.

2024-05-07 14:16 UTC, p3rcypj commented on src/webapp/pages/app/App.tsx
> -
This is subjective but adding blank lines can improve readability for blocks that have multiline components. Another approach would be to abstract the `div#app` into another component so we will have 4 components of one line. Based on [3DBIONOTES PR #214](https://github.com/EyeSeeTea/3DBIONOTES/pull/214#discussion_r1567069654).

2024-05-07 14:17 UTC, p3rcypj commented on src/webapp/pages/app/AppConfig.ts
> +        notifyEmailOnProjectSave: string[];
As we discussed, to be removed

2024-05-07 14:17 UTC, p3rcypj commented on src/app-config.ts
> +        notifyEmailOnProjectSave: [""],
To be removed

2024-05-07 14:24 UTC, p3rcypj requested changes
Thank you, @mariaozamiz, for adding the new component 🙌🏻 Everything looks good! There are just some minor things to be removed but everything is ok and the functionality works perfectly👌🏻

2024-05-09 08:58 UTC, p3rcypj approved these changes
Everything looking good! Thanks!! @mariaozamiz

2024-05-16 07:47 UTC, MiquelAdell approved these changes
working fine, thanks!

2024-05-16 07:48 UTC, merged