Add search OU import, export and search
EyeSeeTea/user-extended-app pull request #283
Opened 2024-05-10 10:09 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/8694ba058

### :memo: Implementation

### :video_camera: Screenshots/Screen capture

https://github.com/EyeSeeTea/user-extended-app/assets/37223065/fd686bd0-a6db-4786-bd87-c487853343bf

<img width="881" alt="Screenshot 2024-05-10 at 11 02 17" src="https://github.com/EyeSeeTea/user-extended-app/assets/37223065/6b9919c8-1317-4cdc-84b0-ad2a4afdd770">
<img width="1352" alt="Screenshot 2024-05-10 at 11 04 06" src="https://github.com/EyeSeeTea/user-extended-app/assets/37223065/b114ac89-6c3e-470e-8cc1-5984e786d464">

### :fire: Testing

#8694ba058

2024-05-16 12:10 UTC, ifoche commented
Task linked: [CU-8694ba058 Add search, import and export "Search OU"](https://app.clickup.com/t/8694ba058)

2024-05-16 12:52 UTC, eperedo requested changes
Thanks for the code @deeonwuli. I'm getting this error after selecting a org unit in the search filter: `"Unknown path property: searchOrganisationUnits.id"`

![image](https://github.com/EyeSeeTea/user-extended-app/assets/461124/70b55a7b-de93-48f5-b924-b9b567f37c8e)

More details in one of my comments, let me know if you any questions.

2024-05-16 12:52 UTC, eperedo commented on src/legacy/models/userList.js
> +    "searchOrganisationUnits[id,code,shortName,displayName]",
Same, `teiSearchOrganisationUnits`

2024-05-16 13:28 UTC, deeonwuli commented on src/legacy/models/userHelpers.js
> +        searchOrganisationsUnits: namesFromCollection(user.dataViewOrganisationUnits, orgUnitsField, toArray),
right

2024-05-16 22:56 UTC, eperedo requested changes
Sorry @deeonwuli but still getting the same error: `"Unknown path property: searchOrganisationUnits.id"` Check my comment for the file `Filters.component.js`

Also I cannot modify the search org. units in the import modal:

[User-Extended-App_import_csv.webm](https://github.com/EyeSeeTea/user-extended-app/assets/461124/4a0ab18e-8e14-4330-8f52-a193fb00e970)

2024-05-16 22:56 UTC, eperedo commented on src/legacy/List/list.store.js
> -    { name: "dataViewOrganisationUnits", sortable: false },
is `dataViewOrganisationUnits` not necessary anymore?

2024-05-16 22:56 UTC, eperedo commented on src/legacy/models/userHelpers.js
> +        teiSearchOrganisationsUnits: namesFromCollection(user.dataViewOrganisationUnits, orgUnitsField, toArray),
We can keep the entity name at the object level, but the dhis2 property name to get the value:

```tsx
searchOrganisationsUnits: namesFromCollection(user.teiSearchOrganisationUnits, orgUnitsField, toArray),
```

2024-05-20 18:22 UTC, eperedo requested changes
We're very close @deeonwuli, right now if you try to import new users it'll send the `searchOrganisationUnits` array, but that's not right since DHIS needs the attribute `teiSearchOrganisationUnits`.

I saw a function `getUserPayloadFromPlainAttributes` in `userHelper.js` where there's a mapping before sending all the payload. I think you can add the attribute in there (if you think there's a better alternative that's ok feel free to do it the best way)

```js
function getUserPayloadFromPlainAttributes(baseUser, userFields) {
  // ...
  return {
    ...userRoot,
teiSearchOrganisationUnits: userRoot.searchOrganisationsUnits ? userRoot.searchOrganisationsUnits : undefined,
    // ...
  };
}
```

2024-05-21 21:04 UTC, eperedo approved these changes
Looks good, thanks @deeonwuli!

2024-05-22 06:12 UTC, merged