Dojo: Replicate Action Refactor
EyeSeeTea/user-extended-app pull request #304
Opened 2024-11-19 20:18 UTC by nshandra

### :pushpin: References

-   **Issue:** [Q4 2024 Project Coding Dojo](https://app.clickup.com/t/8695pt0av)

### :memo: Implementation

Refactor replicate functions:

- Replicate user from template (A final form version is available and will probably be the one to integrate into UEApp)
- Replicate user from table (Updated the new ImportTable for this function)

2024-11-28 08:25 UTC, nshandra commented
@xurxodev putting on draft to remove the demo part from the PR and to add a new feature needed for WIDP:
The password should be random for the replicated users so there are no default creds to abuse.

2024-12-23 07:58 UTC, xurxodev requested changes
thanks @nshandra 

I've found issues to review:

- Non related specially to this PR but UserLogic is really the entity and User is the props. I would expect the names as UserLogic -> User and User -> UserProps
- In the new code affected by this PR that to use  UserRepository, we should change to return the entity from the repository and not the props.

I've added rest of the issues in comments in the code.

2024-12-23 07:58 UTC, xurxodev commented on src/data/repositories/UserD2ApiRepository.ts
> +    public listAllUsernames(options: ListOptions): FutureData<string[]> {
A repository should never return primitive types, this is a code smell that we saw in the coding dojo

In Clean Architecture, a repository should always return entities.

The presentation layer should map user list to get userNames if required.

In this case the entity is UserLogic (can we change to User and User to UserProps?)

2024-12-23 07:58 UTC, xurxodev commented on src/domain/usecases/ListAllUsernamesUseCase.ts
> +import { UseCase } from "../../CompositionRoot";
A use case should never return primitive types, this is a code smell that we saw in the coding dojo

In Clean Architecture, a use case should always return entities.

The presentation layer should map user list to get userNames if required.

In this case the entity is UserLogic (can we change to User and User to UserProps?)

2024-12-23 07:58 UTC, xurxodev commented on src/webapp/components/import-export/ImportTable.tsx
> +                    if (/^[._@-]|[._@-]$/.test(value)) {
These new validations are business rules validations and should be realized in the user domain entity

2024-12-23 07:58 UTC, xurxodev commented on src/webapp/components/replicate/ReplicateUserFromTable.tsx
> +    const { compositionRoot } = useAppContext();
The component should only render. (render logic)

The rest of the presentation logic (manage state, actions, invoke use cases, etc.) should be in a custom hook: useReplicateUserFromTable.

In this custom hook, we should use the user entity, not the user props

2024-12-23 07:58 UTC, xurxodev commented on src/webapp/components/replicate/ReplicateUserFromTemplate.tsx
> +export const ReplicateUserFromTemplate: React.FC<ReplicateUserFromTemplateProps> = props => {
The rest of the presentation logic (manage state, actions, invoke use cases, etc.) should be in a custom hook: useReplicateUserFromTemplate.

In this custom hook, we should use the user entity, not the user props

2024-12-23 07:58 UTC, xurxodev commented on src/webapp/components/replicate/ReplicateUserFromTemplate.tsx
> +
These validations are business rules validations and should be realized in the user domain entity.

To validate you can to try to create a domain entity, call internally to validate a return, for example an Either with the entity or the errors.

You can see these examples:
* https://github.com/EyeSeeTea/malaria-threats-map/blob/c69d08e377d83d56f2d08da54899616b97f5492c/src/domain/entities/Feedback.ts#L36
* https://github.com/EyeSeeTea/coding-dojo/blob/kata/clean-architecture-solution/src/domain/entities/Product.ts

2025-07-24 09:14 UTC, nshandra commented on src/data/repositories/UserD2ApiRepository.ts
> +    public listAllUsernames(options: ListOptions): FutureData<string[]> {
With the proposed changes to `listAllUsernames` and `ListAllUsernamesUseCase.ts` they do the same than `listAllUsers` / `ListAllUsersUseCase`. I switched to using them.

2025-07-24 09:14 UTC, nshandra commented on src/domain/usecases/ListAllUsernamesUseCase.ts
> +import { UseCase } from "../../CompositionRoot";
ListAllUsernamesUseCase was removed.

2025-07-24 09:15 UTC, nshandra commented on src/webapp/components/import-export/ImportTable.tsx
> +                    if (/^[._@-]|[._@-]$/.test(value)) {
Moved to User (former UserLogic) entity

2025-07-24 09:16 UTC, nshandra commented on src/webapp/components/replicate/ReplicateUserFromTable.tsx
> +    const { compositionRoot } = useAppContext();
Moved logic to `useReplicateUserFromTable.ts`

2025-07-24 09:16 UTC, nshandra commented on src/webapp/components/replicate/ReplicateUserFromTemplate.tsx
> +export const ReplicateUserFromTemplate: React.FC<ReplicateUserFromTemplateProps> = props => {
Moved logic to `useReplicateUserFromTemplate.ts`

2025-07-24 09:18 UTC, nshandra commented on src/webapp/components/replicate/ReplicateUserFromTemplate.tsx
> +
Created a new entity `ReplicateTemplate` with the validation logic and some improvements to them.

2025-08-07 08:44 UTC, xurxodev requested changes
thanks @nshandra 

This PR has become quite large.

I've noticed some important issues in the implementation of Clean Architecture and decided to focus on that first. I've left notes about them in the comments.

2025-08-07 08:44 UTC, xurxodev commented on src/data/D2ApiLogger.ts
> +import { UserProps } from "../domain/entities/UserProps";
UserProps should be used outside of the domain. 

You can use User because extends Struct<UserProps> and has the same properties

2025-08-07 08:44 UTC, xurxodev commented on src/data/repositories/UserD2ApiRepository.ts
>      }
A repository always must receive and return entities, not props

2025-08-07 08:44 UTC, xurxodev commented on src/domain/entities/ReplicateTemplate.ts
> +    static validateReplicateCount(value: string): string | undefined {
An entity should validate its invariants in the moment of the construction.

When an entity doesn't validate its invariants, is possible to create an instance in invalid state

the validations should be executed to create or update the entity

2025-08-07 08:44 UTC, xurxodev commented on src/domain/entities/User.ts
> +    static validateUniqueOpenId(users: UserProps[]): boolean {
An entity should validate its invariants in the moment of the construction.

When an entity doesn't validate its invariants, is possible to create an instance in invalid state

the validations should be executed to create or update the entity

2025-08-07 08:44 UTC, xurxodev commented on src/domain/repositories/UserRepository.ts
> +    getCurrent(): FutureData<UserProps>;
A repository always must receive and return entities, not props

2025-08-07 08:44 UTC, xurxodev commented on src/domain/usecases/CopyInUserUseCase.ts
> -    private applyCopyToUsers(usersToUpdate: User[], options: CopyInUserOptions): User[] {
An use case can receive the entity or the props, but if receive the props normally is in creation or modifications, then the use case should create the entity but never pass it directly to repositories.

2025-08-07 08:44 UTC, xurxodev commented on src/domain/usecases/ExportUsersUseCase.ts
> -        users: User[],
An use case can receive the entity or the props, but if receive the props normally is in creation or modifications, then the use case should create the entity but never pass it directly to repositories.

2025-08-07 08:44 UTC, xurxodev commented on src/domain/usecases/GetCurrentUserUseCase.ts
>  export class GetCurrentUserUseCase implements UseCase {
The use case should return always the entity

2025-08-07 08:44 UTC, xurxodev commented on src/domain/usecases/GetUsersByIdsUseCase.ts
> -    public execute(ids: string[]): FutureData<User[]> {
The use case should return always the entity

2025-08-07 08:44 UTC, xurxodev commented on src/domain/usecases/ListUsersUseCase.ts
> -    public execute(options: ListOptions): FutureData<{ pager: Pager; objects: User[] }> {
The use case should return always the entity

2025-08-07 08:44 UTC, xurxodev commented on src/domain/usecases/RemoveUsersUseCase.ts
> +    execute(users: UserProps[]): FutureData<Stats> {
To do this use case more usable from several places is better if receive only userIds, to remove is not necessary all props or entity

2025-08-07 08:44 UTC, xurxodev commented on src/domain/usecases/ReplicateFromTemplateUseCase.ts
> +        const newUsers: UserProps[] = _.times(count, index => {
To replicate a user, we should try to create the entity and to realize the validations in the moment of the creation (using create or build method in the entity with validations)

2025-08-07 08:44 UTC, xurxodev commented on src/webapp/components/import-export/ImportTable.tsx
> +                    const usernameValidationError = User.validateUsername(value);
The validations should be realized in the moment of the creation. It's ok if you want to use the function to validate here instead of try to create the entity but it's necessary to validate again to create the entity to avoid invalid states

2025-09-12 06:58 UTC, xurxodev approved these changes
thanks @nshandra 

In general terms, the code of this PR has improved. There are architecture improvements to do, but as this PR is blocking others, I leave it here for the future.

@adrianq This improvements can be different tasks

- Validations return primitive types like strings. booleans.

Validations should represents an error to avoid interpretations. 
To use throw error or either

- Duplicated validations

There are duplicate validations like username, etc.

Username, email and similar concepts are really domain types and it should modeled using ValueObjects and not primitive types to avoid the primitive obsession code smells and to reuse this types and its validations in different parts of the app

- A lot of static validations 

There are a lot of static public validations that never are called from outside of the entity like ValidateEmail for example.

This maybe solved using value objects

- generateUid() duplicate in use cases and custom hook

Generate uid should be realized only from the domain and to avoid duplicates the best place in in the user domain entity to create.

If the uid is empty then generate it.

* Performance

I've done a simple test of replicate from table and replicate from template, and I have the feeling the poor performance to load the dialogs and to save.
The save in my case is to save one user to replicate.

2025-09-12 12:44 UTC, adrianq commented
Thanks @xurxodev  I have created two tasks to cover your comments:
- This task is regarding the refactors on the code: https://app.clickup.com/t/869af8g88
- This other task is about the performance and is the one with the highest performance: https://app.clickup.com/t/869af8h25 @nshandra has already talked to the two of us and has some ideas about how to improve it. We are merging this PR. Some other PRs will be merged afterwards that include the schemas for 41 so it is much more convenient to start from a new branch from development

2025-09-12 12:44 UTC, merged